OrdererOrgs:
<%_ ordererOrgs.forEach(function(ordererOrg) { _%>
  - Name: <%= ordererOrg.name %>
    Domain: <%= ordererOrg.domain %>
    Specs:
    <%_ ordererOrg.orderers.forEach(function(orderer) { _%>
      - Hostname: <%= orderer.name  %>
    <%_ }) _%>

<%_ }) _%>
