PartyID: 1

General:
  ListenAddress: 0.0.0.0
  ListenPort: 7050
  TLS:
    Enabled: true
    PrivateKey: /node-tls/server.key
    Certificate: /node-tls/server.crt
    RootCAs:
      - /org-tls-ca.pem
    ClientAuthRequired: false
    ClientRootCAs:
  Keepalive:
    ServerMinInterval: 60s
    ServerInterval: 7200s
    ServerTimeout: 20s
  Backoff:
    BaseDelay: 1s
    Multiplier: 1.6
    MaxDelay: 2m
  MaxRecvMsgSize: 104857600
  MaxSendMsgSize: 104857600
  Bootstrap:
    Method: block
    File: /bootstrap/genesis.block
  Cluster:
    SendBufferSize: 100
    ClientCertificate: /node-tls/server.crt
    ClientPrivateKey: /node-tls/server.key
  LocalMSPDir: /node-msp
  LocalMSPID: OrdererOrdererMSP
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  LogSpec: info

FileStore:
  Location: /data

Operations:
  ListenAddress: 0.0.0.0
  ListenPort: 9443
  TLS:
    Enabled: false

Metrics:
  Provider: prometheus
  MetricsLogInterval: 0s

Consensus:
  WALDir: /data/wal