name: "Setup Docker v28"
description: "Downgrade Docker Engine + CLI to v28 on ubuntu-latest"
runs:
  using: "composite"
  steps:
    - name: Downgrade Docker to v28
      shell: bash
      run: |
        set -euxo pipefail

        sudo apt-get update
        sudo apt-get install -y ca-certificates curl
        sudo install -m 0755 -d /etc/apt/keyrings
        sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        sudo chmod a+r /etc/apt/keyrings/docker.asc

        sudo tee /etc/apt/sources.list.d/docker.sources >/dev/null <<EOF
        Types: deb
        URIs: https://download.docker.com/linux/ubuntu
        Suites: $(. /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}")
        Components: stable
        Signed-By: /etc/apt/keyrings/docker.asc
        EOF

        sudo apt-get update
        sudo apt-get install -y --allow-downgrades \
          docker-ce-cli=5:28.0.4-1~ubuntu.24.04~noble \
          docker-ce=5:28.0.4-1~ubuntu.24.04~noble

        docker --version
