OrdererOrgs:
  - Name: <%= rootOrg.organization.name  %>
    Domain: <%= rootOrg.organization.domain  %>
    Specs: <% for(var i=0; i<rootOrg.orderer.instances; i++) {%>
      - Hostname: <%= rootOrg.orderer.prefix %><%= i %><% } %>
