OrdererOrgs:
  - Name: <%= rootOrg.organization.name  %>
    Domain: <%= rootOrg.organization.domain  %>
    Specs: <% rootOrg.orderers.forEach(function(orderer) { %>
      - Hostname: <%= orderer.name  %>
    <% }) -%>
