---
"$schema": https://github.com/softwaremill/fablo/releases/download/0.3.0-unstable/schema.json
networkSettings:
  fabricVersion: 1.4.11
  tls: false
rootOrg:
  organization:
    name: Root
    domain: root.com
ordererOrgs:
  organization:
    name: Orderer
    domain: orderer.com
  orderer:
    prefix: orderer
    type: solo
    instances: 1
orgs:
  - organization:
      name: Org1
      domain: org1.com
    peer:
      instances: 2
  - organization:
      name: Org2
      domain: org2.com
    peer:
      instances: 1
channels:
  - name: my-channel1
    orgs:
      - name: Org1
        peers:
          - peer0
          - peer1
      - name: Org2
        peers:
          - peer0
chaincodes:
  - name: or-policy-chaincode
    version: 0.0.1
    lang: node
    channel: my-channel1
    init: '{"Args":[]}'
    endorsement: OR('Org1MSP.member', 'Org2MSP.member')
    directory: "./chaincodes/chaincode-kv-node-1.4"
    privateData:
      - name: org1-collection
        orgNames:
          - Org1
  - name: and-policy-chaincode
    version: 0.0.1
    lang: node
    channel: my-channel1
    endorsement: AND('Org1MSP.member', 'Org2MSP.member')
    directory: "./chaincodes/chaincode-kv-node-1.4"
    privateData:
      - name: org1-collection
        orgNames:
          - Org1
