---
"$schema": https://github.com/softwaremill/fablo/releases/download/0.3.0-unstable/schema.json
networkSettings:
  fabricVersion: 2.3.1
  tls: true
  monitoring:
    loglevel: info
rootOrg:
  organization:
    name: Orderer
    domain: root.com
  orderer:
    type: raft
    instances: 3
orgs:
  - organization:
      name: Org1
      domain: org1.com
    # this is the default configuration for peers that may be used in other orgs
    peer: &defaultPeerConfig
      prefix: peer
      instances: 2
      anchorPeerInstances: 2
      db: LevelDb
  - organization:
      name: Org2
      domain: org2.com
    peer: *defaultPeerConfig
channels:
  - name: my-channel1
    orgs:
      - name: Org1
        peers:
          - peer0
      - name: Org2
        peers:
          - peer0
  - name: my-channel2
    orgs:
      - name: Org1
        peers:
          - peer1
      - name: Org2
        peers:
          - peer1
chaincodes:
  - name: chaincode1
    version: 0.0.1
    lang: node
    channel: my-channel1
    endorsement: OR ('Org1MSP.member', 'Org2MSP.member')
    directory: "./chaincodes/chaincode-kv-node"
  - name: chaincode2
    version: 0.0.1
    lang: java
    channel: my-channel2
    endorsement: OR ('Org1MSP.member', 'Org2MSP.member')
    directory: "./chaincodes/chaincode-java-simple"
