

---
Organizations:

  - &OrdererOrdererMSP
    Name: Orderer
    SkipAsForeign: false
    ID: OrdererOrdererMSP
    MSPDir: ./crypto/ordererOrganizations/orderer.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: OR('OrdererOrdererMSP.member')
      Writers:
        Type: Signature
        Rule: OR('OrdererOrdererMSP.member')
      Admins:
        Type: Signature
        Rule: OR('OrdererOrdererMSP.admin')
    OrdererEndpoints:
      - id=0,broadcast,orderer-router:7050
      - id=0,deliver,orderer-assembler:7053



  - &Org1MSP
    Name: Org1
    ID: Org1MSP
    MSPDir: ./crypto/peerOrganizations/org1.example.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: OR('Org1MSP.member')
      Writers:
        Type: Signature
        Rule: OR('Org1MSP.member')
      Endorsement:
        Type: Signature
        Rule: OR('Org1MSP.member')
      Admins:
        Type: Signature
        Rule: OR('Org1MSP.admin')
    AnchorPeers:


Capabilities:
  Channel: &ChannelCapabilities
    V3_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_5: true

Application: &ApplicationDefaults
  ACLs:
    _lifecycle/CheckCommitReadiness: /Channel/Application/Writers
    _lifecycle/CommitChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinition: /Channel/Application/Writers
    _lifecycle/QueryChaincodeDefinitions: /Channel/Application/Writers
    lscc/ChaincodeExists: /Channel/Application/Readers
    lscc/GetDeploymentSpec: /Channel/Application/Readers
    lscc/GetChaincodeData: /Channel/Application/Readers
    lscc/GetInstantiatedChaincodes: /Channel/Application/Readers
    qscc/GetChainInfo: /Channel/Application/Readers
    qscc/GetBlockByNumber: /Channel/Application/Readers
    qscc/GetBlockByHash: /Channel/Application/Readers
    qscc/GetTransactionByID: /Channel/Application/Readers
    qscc/GetBlockByTxID: /Channel/Application/Readers
    cscc/GetConfigBlock: /Channel/Application/Readers
    cscc/GetChannelConfig: /Channel/Application/Readers
    peer/Propose: /Channel/Application/Writers
    peer/ChaincodeToChaincode: /Channel/Application/Writers
    event/Block: /Channel/Application/Readers
    event/FilteredBlock: /Channel/Application/Readers
  Organizations:

    - *Org1MSP

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: ANY Admins
    Endorsement:
      Type: ImplicitMeta
      Rule: ANY Endorsement
    LifecycleEndorsement:
      Type: Signature
      Rule: OR('Org1MSP.member')
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: arma
  BatchTimeout: 500ms
  BatchSize:
    MaxMessageCount: 3500
    AbsoluteMaxBytes: 16 MB
    PreferredMaxBytes: 4 MB
  MaxChannels: 0
  ConsenterMapping:

    - ID: 1
      Host: orderer-consenter
      Port: 7052
      MSPID: OrdererOrdererMSP
      Identity: ./crypto/ordererOrganizations/orderer.example.com/orderers/party1/consenter.orderer.example.com/msp/signcerts/consenter.orderer.example.com-cert.pem
      ClientTLSCert: ./crypto/ordererOrganizations/orderer.example.com/orderers/party1/consenter.orderer.example.com/tls/server.crt
      ServerTLSCert: ./crypto/ordererOrganizations/orderer.example.com/orderers/party1/consenter.orderer.example.com/tls/server.crt

  Organizations:

    - *OrdererOrdererMSP

  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
    BlockValidation:
      Type: ImplicitMeta
      Rule: ANY Writers
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: ANY Readers
    Writers:
      Type: ImplicitMeta
      Rule: ANY Writers
    Admins:
      Type: ImplicitMeta
      Rule: MAJORITY Admins
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  OrgsChannel:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Arma:
        Path: ./crypto/shared_config.binpb
    Consortium: SampleConsortium
    Application:
      <<: *ApplicationDefaults
