name: Publish docker image

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
            prefix=
            suffix=
          tags: |
            type=semver,pattern={{version}}

      - name: Validate release version
        run: |
          ./check-if-fabrica-version-matches-with-tag.sh ${{ steps.meta.outputs.tags }}

      - name: Build Fabrica
        run: |
          shellcheck --version && \
          yamllint -v && \
          npm install && \
          npm run build:dist

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Setup version details
        run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)
          BUILD_DATE=$(date +'%Y-%m-%d-%H:%M:%S')
          echo "VERSION_DETAILS=$BUILD_DATE-$COMMIT_HASH" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ${{ github.workspace }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            VERSION_DETAILS=${{ env.VERSION_DETAILS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
