name: Publish on merge to main

on:
  push:
    branches:
      - main

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push Docker image
        run: |
          shellcheck --version
          yamllint -v
          npm install
          ./fablo-build.sh --push
      
      - name: Build and push node chaincode
        run: |
          FABLO_VERSION=$(cat package.json | jq -r '.version')
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag "ghcr.io/fablo-io/fablo-kv-node-chaincode-sample:$FABLO_VERSION" \
            --push \
            samples/chaincodes/chaincode-kv-node
