name: Publish on merge to main

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: softwaremill/fablo

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Fablo
        run: |
          shellcheck --version
          yamllint -v
          npm install
          ./fablo-build.sh

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        run: |
          FABLO_VERSION=$(jq -r '.version' <"$GITHUB_WORKSPACE/package.json")
          docker push softwaremill/fablo:"$FABLO_VERSION"
