name: Release on tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version from tag and update tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          VERSION=${TAG:1}
          echo "TAG: $TAG"
          echo "VERSION: $VERSION"
          ./bump_version.sh set "$VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -a -m "Set version from tag: $TAG"
          git tag -a "$TAG" -m "Release $TAG"
          git push origin "$TAG"

      - name: Build Fablo
        run: |
          shellcheck --version
          yamllint -v
          npm install
          ./fablo-build.sh

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker image
        run: |
          FABLO_VERSION=$(jq -r '.version' <"$GITHUB_WORKSPACE/package.json")
          docker push softwaremill/fablo:"$FABLO_VERSION"

      - name: Create GitHub Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            docs/schema.json
            fablo.sh

      - name: Set next development version
        run: |
          ./bump_version.sh unstable
          git commit -a -m "Set new development version: $NEW_VERSION"
          git push origin HEAD
